Repository OpenSimulationInterface/osi-sensor-model-packaging, pull requests merged in 2023-06, with the labels that each got.

#95 Fix errors in rotation function in OSMPDummySensor
  examples/OSMPDummySensor/OSMPDummySensor.cpp
  examples/OSMPDummySource/OSMPDummySource.cpp
Labels: bug, ReadyToMerge

#91 Doc/protobuf build instructions
  doc/setup/build_install_example.adoc
Labels: documentation, ReadyToMerge

#99 Add streaming update consumer model type and interface
  doc/osi-sensor-model-packaging_spec.adoc
  doc/spec/model_types.adoc
  doc/spec/streaming_update_inputs.adoc
Labels: ReadyToMerge
